/**
 * assets.mjs — the asset library: fingerprint every file in assets/, and publish it to
 * https://assets.servantium.com (Cloudflare R2 bucket `servantium-assets`).
 *
 *   node scripts/assets.mjs manifest          write assets.manifest.json from the files in assets/
 *   node scripts/assets.mjs check             fail if assets.manifest.json is out of date
 *   node scripts/assets.mjs publish [--dry-run]
 *                                             upload every file the bucket doesn't have yet; on a
 *                                             clean, up-to-date main, also refresh the catalogue
 *   node scripts/assets.mjs verify            fail if any file in the manifest isn't live
 *
 * THE RULE (docs/asset-library.md): every file gets a permanent address that includes a
 * fingerprint of its contents — `logo/servantium-logo-white.<hash>.png`. A changed file gets a new
 * address; nothing is ever overwritten or deleted. So an email or a deck keeps showing exactly what
 * it was made with, and the files can be cached for a year. The only files that change in place
 * are the catalogue, `manifest.json` and `index.html`, which say which address is current.
 *
 * Publishing uses wrangler with the Cloudflare credentials already in your shell. It needs
 * "Workers R2 Storage: Edit" on the Servantium account. It never deletes anything.
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, extname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ASSETS = join(ROOT, 'assets');
const MANIFEST = join(ROOT, 'assets.manifest.json');

export const ORIGIN = 'https://assets.servantium.com';
export const BUCKET = 'servantium-assets';
const HASH_LENGTH = 10;

const IMMUTABLE = 'public, max-age=31536000, immutable';
const USER_AGENT = 'servantium-assets (+https://github.com/servantium/servantium-design-system)';

/**
 * Keep search engines out: these are brand files for email and embeds, not pages. Mail clients'
 * image proxies fetch on a reader's behalf and don't read robots.txt, so emails are unaffected.
 * Link-preview bots are let in, so a social card hosted here still renders when a page is shared.
 */
const ROBOTS = `# assets.servantium.com: Servantium's brand files, for email and embeds. Not for search.
User-agent: Twitterbot
User-agent: facebookexternalhit
User-agent: LinkedInBot
User-agent: Slackbot
Allow: /

User-agent: *
Disallow: /
`;
const CATALOGUE = 'public, max-age=300';

const TYPES = {
  '.svg': 'image/svg+xml', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.webp': 'image/webp', '.gif': 'image/gif', '.avif': 'image/avif', '.ico': 'image/x-icon',
  '.pdf': 'application/pdf', '.woff2': 'font/woff2', '.json': 'application/json',
};

// ── Fingerprinting ──────────────────────────────────────────────────────────────────────────────
function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    if (name.startsWith('.')) return [];
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

/** Asset path (e.g. `logo/servantium-logo.png`) → its permanent key and details. */
export function buildManifest() {
  const assets = {};
  for (const file of walk(ASSETS).sort()) {
    const path = relative(ASSETS, file).split(sep).join('/');
    const ext = extname(path).toLowerCase();
    const type = TYPES[ext];
    if (!type) throw new Error(`${path}: ${ext || 'no extension'} isn't a type the library serves (${Object.keys(TYPES).join(' ')})`);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*(?:\/[a-z0-9]+(?:-[a-z0-9]+)*)*\.[a-z0-9]+$/.test(path)) {
      throw new Error(`${path}: use lower case, words joined by hyphens, one dot before the extension`);
    }
    const bytes = readFileSync(file);
    const sha256 = createHash('sha256').update(bytes).digest('hex');
    const key = `${path.slice(0, -ext.length)}.${sha256.slice(0, HASH_LENGTH)}${ext}`;
    assets[path] = { key, type, bytes: bytes.length, sha256 };
  }
  return {
    $comment: 'GENERATED by `npm run manifest` in packages/brand — do not edit. Each asset\'s permanent public address is origin + "/" + key. See docs/asset-library.md.',
    origin: ORIGIN,
    assets,
  };
}

const serialise = (m) => `${JSON.stringify(m, null, 2)}\n`;

// ── Publishing ──────────────────────────────────────────────────────────────────────────────────
/**
 * Is the file at this address? `bypassCache` asks with a throwaway query string, so the check never
 * reaches Cloudflare's cache for the real address. Publishing needs that: asking for an address
 * before its file exists would cache a "not found" for it. Verifying doesn't: it wants the answer
 * a recipient would get.
 */
async function status(key, { bypassCache = false } = {}) {
  try {
    const url = `${ORIGIN}/${key}${bypassCache ? `?publish-check=${Date.now()}` : ''}`;
    const res = await fetch(url, { method: 'HEAD', headers: { 'user-agent': USER_AGENT } });
    return res.status;
  } catch (e) {
    return `unreachable (${e.cause?.code ?? e.message})`; // the domain isn't reachable yet: treat as missing
  }
}

const isLive = async (key, opts) => (await status(key, opts)) === 200;

function put(key, file, type, cacheControl) {
  execFileSync('npx', ['--yes', 'wrangler', 'r2', 'object', 'put', `${BUCKET}/${key}`, '--file', file, '--remote',
    '--content-type', type, '--cache-control', cacheControl], { stdio: ['ignore', 'ignore', 'inherit'] });
}

const git = (...args) => execFileSync('git', ['--no-optional-locks', ...args], { cwd: ROOT, encoding: 'utf8' }).trim();

/** The catalogue only moves forward from reviewed work: exactly GitHub's main, with no local changes. */
function onPublishedMain() {
  try {
    execFileSync('git', ['fetch', '--quiet', 'origin', 'main'], { cwd: ROOT });
    const dirty = git('status', '--porcelain', '--', '.');
    const level = git('rev-parse', 'HEAD') === git('rev-parse', 'origin/main');
    return !dirty && level;
  } catch {
    return false;
  }
}

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function catalogueHtml(m) {
  const groups = {};
  for (const [path, a] of Object.entries(m.assets)) (groups[path.split('/')[0]] ??= []).push([path, a]);
  const rows = Object.entries(groups).map(([group, items]) => `
<h2>${esc(group)}</h2>
<div class="grid">${items.map(([path, a]) => {
    const url = `${m.origin}/${a.key}`;
    const preview = a.type.startsWith('image/') ? `<div class="thumb"><img src="${esc(a.key)}" alt="" loading="lazy"></div>` : '<div class="thumb file">file</div>';
    return `<figure>${preview}<figcaption><b>${esc(path)}</b><span>${(a.bytes / 1024).toFixed(1)} KB · ${esc(a.type)}</span><code>${esc(url)}</code></figcaption></figure>`;
  }).join('')}</div>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Servantium assets</title>
<style>
:root{--bg:#F4F6F5;--card:#fff;--ink:#17201B;--ink2:#4A564F;--rule:#DCE3DF;--forest:#023E25;--check:#E9EDEB}
@media (prefers-color-scheme:dark){:root{--bg:#0E1512;--card:#151E1A;--ink:#E7EEEA;--ink2:#A9B7AF;--rule:#2A3831;--check:#1B2621}}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 system-ui,sans-serif;padding:32px 16px}
main{max-width:1100px;margin:0 auto} h1{margin:0 0 4px} p{color:var(--ink2);margin:0 0 24px;max-width:70ch}
h2{font-size:13px;letter-spacing:1.2px;text-transform:uppercase;color:var(--ink2);margin:32px 0 12px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px}
figure{margin:0;background:var(--card);border:1px solid var(--rule);border-radius:10px;overflow:hidden;min-width:0}
.thumb{height:120px;display:grid;place-items:center;padding:12px;background:repeating-conic-gradient(var(--check) 0 25%,transparent 0 50%) 0 0/16px 16px}
.thumb img{max-width:100%;max-height:96px}.file{color:var(--ink2)}
figcaption{display:grid;gap:2px;padding:10px 12px;font-size:13px}figcaption span{color:var(--ink2)}
code{font-size:11px;word-break:break-all;color:var(--ink2)}
</style></head><body><main>
<h1>Servantium assets</h1>
<p>Servantium's own brand files. Every address is permanent: a changed file gets a new address, and old ones keep working. <a href="manifest.json">manifest.json</a> lists the current address of each file. Other companies' logos aren't kept here.</p>
${rows}
</main></body></html>
`;
}

async function publish({ dryRun }) {
  const m = buildManifest();
  const current = existsManifest();
  if (serialise(m) !== current) throw new Error('assets.manifest.json is out of date: run `npm run manifest` and commit it first');

  let uploaded = 0;
  let skipped = 0;
  for (const [path, a] of Object.entries(m.assets)) {
    if (await isLive(a.key, { bypassCache: true })) { skipped++; continue; }
    console.log(`${dryRun ? 'would upload' : 'upload'}  ${a.key}`);
    if (!dryRun) put(a.key, join(ASSETS, path), a.type, IMMUTABLE);
    uploaded++;
  }
  console.log(`${uploaded} ${dryRun ? 'to upload' : 'uploaded'}, ${skipped} already live`);

  // robots.txt is fixed policy, not reviewed content, so it goes up from any branch.
  const robotsDir = mkdtempSync(join(tmpdir(), 'servantium-robots-'));
  writeFileSync(join(robotsDir, 'robots.txt'), ROBOTS);
  console.log(`${dryRun ? 'would refresh' : 'refresh'}  robots.txt`);
  if (!dryRun) put('robots.txt', join(robotsDir, 'robots.txt'), 'text/plain; charset=utf-8', CATALOGUE);

  if (!onPublishedMain()) {
    console.log('Catalogue not refreshed: that happens only from a clean checkout of GitHub\'s main.');
    return;
  }
  const dir = mkdtempSync(join(tmpdir(), 'servantium-assets-'));
  const publicManifest = {
    origin: m.origin,
    commit: git('rev-parse', 'HEAD'),
    assets: Object.fromEntries(Object.entries(m.assets).map(([p, a]) => [p, { url: `${m.origin}/${a.key}`, type: a.type, bytes: a.bytes, sha256: a.sha256 }])),
  };
  writeFileSync(join(dir, 'manifest.json'), serialise(publicManifest));
  writeFileSync(join(dir, 'index.html'), catalogueHtml(m));
  console.log(`${dryRun ? 'would refresh' : 'refresh'}  manifest.json, index.html`);
  if (!dryRun) {
    put('manifest.json', join(dir, 'manifest.json'), 'application/json', CATALOGUE);
    put('index.html', join(dir, 'index.html'), 'text/html; charset=utf-8', CATALOGUE);
  }
}

/**
 * A file counts as missing only if it still isn't there after a few tries. From CI's data-centre
 * addresses, Cloudflare now and then refuses or drops a request, so one bad answer isn't proof.
 */
async function verify() {
  const m = JSON.parse(existsManifest());
  const missing = [];
  for (const a of Object.values(m.assets)) {
    let s = await status(a.key);
    for (let attempt = 1; s !== 200 && attempt <= 3; attempt++) {
      await new Promise((r) => setTimeout(r, 2000 * attempt));
      s = await status(a.key);
    }
    if (s !== 200) missing.push(`${a.key} (${s})`);
  }
  if (missing.length) {
    console.error(`${missing.length} asset(s) aren't live at ${ORIGIN} — run \`npm run publish\` in packages/brand:\n  ${missing.join('\n  ')}`);
    process.exit(1);
  }
  console.log(`all ${Object.keys(m.assets).length} assets are live at ${ORIGIN}`);
}

function existsManifest() {
  try { return readFileSync(MANIFEST, 'utf8'); } catch { return ''; }
}

// ── CLI ─────────────────────────────────────────────────────────────────────────────────────────
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [cmd = 'manifest', ...flags] = process.argv.slice(2);
  const run = {
    manifest: () => { writeFileSync(MANIFEST, serialise(buildManifest())); console.log(`wrote assets.manifest.json`); },
    check: () => {
      if (serialise(buildManifest()) !== existsManifest()) {
        console.error('assets.manifest.json is out of date: run `npm run manifest` in packages/brand and commit it');
        process.exit(1);
      }
      console.log('assets.manifest.json is current');
    },
    publish: () => publish({ dryRun: flags.includes('--dry-run') }),
    verify,
  }[cmd];
  if (!run) { console.error(`unknown command "${cmd}" — manifest · check · publish · verify`); process.exit(1); }
  await run();
}
