/**
 * sync-tokens.mjs — copies Verdant's colour and font tokens into a TypeScript module for email.
 *
 * Email can't use CSS custom properties: most clients strip <style>, and Outlook ignores var()
 * entirely, so every colour has to be written inline as a literal hex. This reads the literals out
 * of @servantium/verdant's tokens.css — the SAME file every website and the portal use — and writes
 * them to src/tokens.generated.ts. Change a colour in Verdant, run `npm run build` here, and the
 * emails follow. Nothing in this package defines a brand colour of its own.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const css = readFileSync(require.resolve('@servantium/verdant/tokens.css'), 'utf8');

const tokens = {};
for (const m of css.matchAll(/--(color-[a-z0-9-]+|font-[a-z0-9-]+)\s*:\s*([^;]+);/g)) {
  const [, name, raw] = m;
  const value = raw.trim();
  // Colours: literal hex only — rgba() tokens are overlays for the web and have no email meaning.
  if (name.startsWith('color-') && !/^#[0-9a-f]{3,8}$/i.test(value)) continue;
  if (!(name in tokens)) tokens[name] = value;
}

const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const lines = Object.entries(tokens).map(([k, v]) => `  ${camel(k)}: ${JSON.stringify(v)},`);

writeFileSync(
  join(HERE, '../src/tokens.generated.ts'),
  `// GENERATED by scripts/sync-tokens.mjs from @servantium/verdant/tokens.css — do not edit.\n` +
    `// Change the token in Verdant and run \`npm run tokens\`.\n` +
    `export const verdant = {\n${lines.join('\n')}\n} as const;\n`,
);
console.log(`synced ${lines.length} tokens from verdant`);
